# Generated by Django 4.0.6 on 2022-07-13 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='dive',
            field=models.CharField(choices=[('front-wheel drive', 'front-wheel drive'), ('rear-wheel drive', 'rear-wheel drive'), ('four-wheel drive', 'four-wheel drive')], default=1, max_length=30, verbose_name='Drive'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.PositiveIntegerField(verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='car',
            name='seller',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='car',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='Views'),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.PositiveIntegerField(verbose_name='Year of car manufacture'),
        ),
    ]
