# Generated by Django 4.0.6 on 2022-07-13 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_car_dive_alter_car_price_alter_car_seller_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='dive',
            new_name='drive',
        ),
    ]
